import type { NextPage } from 'next'
import { WithNothingLayout } from '../../layout/BaseLayout'
import LoginContainer from '../../containers/LoginContainer'
import Head from 'next/head'

const Login: NextPage = () => {
  return (
    <>
      <Head>
        <title>房地產網站 | 登入</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/yuantai.ico" />
      </Head>
      <LoginContainer />
    </>
  )
}

export default WithNothingLayout(Login)
