import type { NextPage } from 'next'
import { WithSideBarProtected } from '../../layout/BaseLayout'
import AdminHome from '../../containers/AdminHome'
import Head from 'next/head'
import { useEffect } from 'react'
import { useDispatch } from 'react-redux'
import { onPageChange } from '../../store/slice/sideBar'

const Admin: NextPage = () => {
  const dispatch = useDispatch()
  useEffect(() => {
    dispatch(
      onPageChange('none')
    )
  }, [])
  return (
    <>
      <Head>
        <title>房地產網站 | 後台</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/yuantai.ico" />
      </Head>
      <AdminHome />
    </>
  )
}

export default WithSideBarProtected(Admin)
