import type { NextPage } from 'next'
import { WithSideBarProtected } from '../../../layout/BaseLayout'
import Head from 'next/head'

const Cases: NextPage = () => {
  return (
    <>
      <Head>
        <title>房地產網站 | 案件列表</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/yuantai.ico" />
      </Head>
      <p>案件</p>
    </>
  )
}

export default WithSideBarProtected(Cases)
